version: 2
updates:
    - package-ecosystem: gradle
      directory: '/android'
      schedule:
          interval: daily
      target-branch: 'main'
      labels: ['dependabot']
      open-pull-requests-limit: 10
      ignore:
          - dependency-name: 'rollup'
          - dependency-name: 'browserify'
          - dependency-name: '@babel/runtime'